[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F18200"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF4E8"
textColor = "#262626"
font = "sans serif"
